export const GET_USER_LOCATION_REQUEST = 'GET_USER_LOCATION_REQUEST';
export const GET_USER_LOCATION_SUCCESS = 'GET_USER_LOCATION_SUCCESS';
export const GET_USER_LOCATION_FAIL = 'GET_USER_LOCATION_FAIL';

export const GET_USER_WEATHER_REQUEST = 'GET_USER_WEATHER_REQUEST';
export const GET_USER_WEATHER_SUCCESS = 'GET_USER_WEATHER_SUCCESS';
export const GET_USER_WEATHER_FAIL = 'GET_USER_WEATHER_FAIL';

export const GET_LOCATION_REQUEST = 'GET_LOCATION_REQUEST';
export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS';
export const GET_LOCATION_FAIL = 'GET_LOCATION_FAIL';

export const GET_WEATHER_DETAILS_REQUEST = 'GET_WEATHER_DETAILS_REQUEST';
export const GET_WEATHER_DETAILS_SUCCESS = 'GET_WEATHER_DETAILS_SUCCESS';
export const GET_WEATHER_DETAILS_FAIL = 'GET_WEATHER_DETAILS_FAIL';
export const GET_WEATHER_DETAILS_CLEAR = 'GET_WEATHER_DETAILS_CLEAR';
